Repository nextsimhub/nextsimdg, pull requests merged in 2023-09, with the labels that each got.

#374 A const return value makes no sense.
  core/src/include/ModelArray.hpp
Labels: bug

#408 fix CMakeLists.txt to build nextsim
  CMakeLists.txt
  cmake/Findxios.cmake
Labels: bug

#364 Issue290 Make the rectNxM restart files valid again
  core/test/ModelArray_test.cpp
  core/test/ParaGrid_test.cpp
  run/init_rect30x30.nc
  run/make_init.py
Labels: bug, update

#414 fix build for gfortran
  core/test/CMakeLists.txt
  core/test/XiosInit_test.cpp
Labels: bug

#416 Fix and tidy tests
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/XiosBuild_test.cpp
  core/test/XiosDisabled_test.cpp
  core/test/XiosInit_test.cpp
  physics/test/CMakeLists.txt
Labels: bug, ICCS
