Repository nextsimhub/nextsimdg, pull requests merged in 2023-11, with the labels that each got.

#308 Issue307 confighelp
  physics/src/modules/ConfiguredOcean.cpp
Labels: bug, documentation

#438 Issue 427 Documenting the Time classes
  core/src/include/Time.hpp
Labels: documentation, enhancement

#437 Remove devgrid files and usage
  core/src/CMakeLists.txt
  core/src/DevGridIO.cpp
  core/src/Model.cpp
  core/src/StructureFactory.cpp
  core/src/include/DevGridIO.hpp
  core/src/include/IDevGridIO.hpp
  core/src/modules/DevGrid.cpp
  core/src/modules/IStructureModule.cpp
  core/src/modules/include/DevGrid.hpp
  core/src/modules/include/RectangularGrid.hpp
  core/test/CMakeLists.txt
  core/test/DevGrid_example.cpp
  core/test/DevGrid_test.cpp
  physics/test/CMakeLists.txt
  run/init_rect10x10.nc
  run/make_init_rect10x10.py
  run/run_rect10x10.sh
Labels: enhancement, ICCS

#441 Explicitly correct the restart file land mask.
  run/make_init25kmNH.py
Labels: bug, ICCS

#319 A demo case for single column thermodynamics
  core/src/PrognosticData.cpp
  core/src/include/MonthlyCubicBSpline.hpp
  core/test/CMakeLists.txt
  core/test/MonthlyCubicBSpline_test.cpp
  physics/src/CMakeLists.txt
  physics/src/modules/AtmosphereBoundaryModule.cpp
  physics/src/modules/CCSMIceAlbedo.cpp
  physics/src/modules/ConstantOceanBoundary.cpp
  physics/src/modules/FiniteElementFluxes.cpp
  physics/src/modules/IIceAlbedoModule.cpp
  physics/src/modules/MU71Albedo.cpp
  physics/src/modules/MU71Atmosphere.cpp
  physics/src/modules/SMU2IceAlbedo.cpp
  physics/src/modules/SMUIceAlbedo.cpp
  physics/src/modules/ThermoIce0.cpp
  physics/src/modules/include/CCSMIceAlbedo.hpp
  physics/src/modules/include/IIceAlbedo.hpp
  physics/src/modules/include/MU71Albedo.hpp
  physics/src/modules/include/MU71Atmosphere.hpp
  physics/src/modules/include/SMU2IceAlbedo.hpp
  physics/src/modules/include/SMUIceAlbedo.hpp
  physics/src/modules/include/ThermoWinton.hpp
  physics/test/CMakeLists.txt
  run/column_pp.py
  run/config_column.cfg
  run/init_25km_NH.nc
  run/make_init25kmNH.py
  run/make_init_column.py
  run/run_june23.sh
Labels: enhancement, ICCS

#446 Remove the binary netCDF files from the repo.
  run/init_25km_NH.nc
  run/init_rect20x30.nc
  run/init_rect30x30.nc
  run/init_topaz128x128.nc
Labels: enhancement

#445 Section about documentation in README
  .readthedocs.yaml
  README.md
  docs/changelog.rst
  docs/conf.py
  docs/environment.yml
  docs/getting_started.rst
  docs/index.rst
  docs/model-components.rst
  docs/numerical-implementation.rst
  docs/outputs-diagnostics.rst
  docs/overview.rst
  requirements.txt
Labels: documentation

#449 Issue347 nextsimlib
  CMakeLists.txt
  core/src/CMakeLists.txt
  core/test/CMakeLists.txt
  dynamics/tests/CMakeLists.txt
  physics/src/CMakeLists.txt
  physics/test/CMakeLists.txt
Labels: ICCS
