Repository nextsimhub/nextsimdg, pull requests merged in 2023-08, with the labels that each got.

#353 Remove homebrew extractions from the test workflows
  .github/workflows/clang-compile-tests.yml
Labels: bug

#263 Issue261 missingdata
  core/src/DevGridIO.cpp
  core/src/MissingData.cpp
  core/src/Model.cpp
  core/src/ModelComponent.cpp
  core/src/ParaGridIO.cpp
  core/src/RectGridIO.cpp
  core/src/include/MissingData.hpp
  core/src/include/Model.hpp
  core/src/include/ModelComponent.hpp
  core/test/CMakeLists.txt
  physics/src/modules/include/FluxConfiguredAtmosphere.hpp
Labels: enhancement

#270 Issue267 dummythermo
  physics/src/IceGrowth.cpp
  physics/src/modules/IceThermodynamicsModule.cpp
  physics/src/modules/LateralIceSpreadModule.cpp
  physics/src/modules/include/DummyIceSpread.hpp
  physics/src/modules/include/DummyIceThermodynamics.hpp
  physics/test/IceGrowth_test.cpp
Labels: enhancement

#358 Fix issue 357 by adding include<tuple>
  physics/src/modules/include/IIceAlbedo.hpp
Labels: bug

#362 Issue361 era5_topaz4_maker.py bilinear interpolation
  run/era5_topaz4_maker.py
Labels: bug, update

#340 Issue338 no thermo
  core/src/ConfigurationHelpPrinter.cpp
  core/src/include/ConfigurationHelp.hpp
  core/src/include/ConfigurationHelpPrinter.hpp
  physics/src/IceGrowth.cpp
  physics/src/include/IceGrowth.hpp
  physics/test/IceGrowth_test.cpp
Labels: enhancement

#284 Issuexxx thermoice0 test
  physics/src/modules/ThermoIce0.cpp
  physics/test/ThermoIce0_test.cpp
Labels: enhancement, ICCS

#298 Issue296 zindexanslayer test
  core/test/ModelArray_test.cpp
  core/test/testmodelarraydetails/ModelArrayDetails.cpp
  core/test/testmodelarraydetails/include/ModelArrayDetails.hpp
  core/test/testmodelarraydetails/include/ModelArrayTypedefs.hpp
Labels: enhancement, ICCS
