Repository nextsimhub/nextsimdg, pull requests merged in 2023-06, with the labels that each got.

#282 Issue238 ice minima
  core/test/CMakeLists.txt
  physics/src/CMakeLists.txt
  physics/src/IceGrowth.cpp
  physics/src/IceMinima.cpp
  physics/src/MinimumIce.cpp
  physics/src/include/IceGrowth.hpp
  physics/src/include/IceMinima.hpp
  physics/src/include/MinimumIce.hpp
  physics/src/modules/ThermoIce0.cpp
  physics/src/modules/ThermoWinton.cpp
  physics/src/modules/include/ILateralIceSpread.hpp
  physics/test/CMakeLists.txt
  physics/test/IceMinima_test.cpp
Labels: enhancement

#329 Issue328 winton bugs
  physics/src/IceGrowth.cpp
  physics/src/modules/ThermoWinton.cpp
  physics/test/IceGrowth_test.cpp
  physics/test/ThermoWintonTemperature_test.cpp
Labels: bug

#302 Adding a Pull Request Template
  .github/pull_request_template.md
Labels: enhancement, ICCS
