Repository nextsimhub/nextsimdg, pull requests merged in 2024-01, with the labels that each got.

#465 Persist the grid coordinates
  core/src/Model.cpp
  core/src/ModelMetadata.cpp
  core/src/ParaGridIO.cpp
  core/src/RectGridIO.cpp
  core/src/finitevolume/ModelArrayDetails.cpp
  core/src/finitevolume/include/ModelArrayDetails.hpp
  core/src/finitevolume/include/ModelArrayTypedefs.hpp
  core/src/include/ModelArray.hpp
  core/src/include/ModelMetadata.hpp
  core/src/include/gridNames.hpp
  core/test/ParaGrid_test.cpp
  core/test/RectGrid_test.cpp
Labels: enhancement, ICCS

#464 Remove the need for smesh files
  core/src/modules/DynamicsModule/Dynamics.cpp
  dynamics/src/ParametricMesh.cpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/ParametricMesh.hpp
  dynamics/tests/25km_NH.smesh
  dynamics/tests/CMakeLists.txt
  dynamics/tests/FakeSmeshData.cpp
  dynamics/tests/FakeSmeshData.hpp
  dynamics/tests/ParametricMesh_test.cpp
  run/25km_NH_newmask.smesh
  run/init_topaz128x128.smesh
  run/tmp-benchmark.smesh
Labels: documentation, enhancement, ICCS

#472 Fix the single column thermo crash
  core/src/Logged.cpp
  core/src/include/Logged.hpp
Labels: bug

#294 Issue239 restart
  core/src/CMakeLists.txt
  core/src/DevStep.cpp
  core/src/Model.cpp
  core/src/ModelConfig.cpp
  core/src/PDWriter.cpp
  core/src/include/DevStep.hpp
  core/src/include/Model.hpp
  core/src/include/ModelConfig.hpp
  core/src/include/PrognosticData.hpp
  core/test/PrognosticData_test.cpp
Labels: enhancement

#474 Duration defaults
  core/src/DevStep.cpp
  core/src/Model.cpp
  core/src/include/DevStep.hpp
  core/test/Time_test.cpp
Labels: bug, documentation

#350 Document and test configuration help
  CMakeLists.txt
  core/src/CommandLineParser.cpp
  core/test/CMakeLists.txt
  core/test/testHelpConfig.sh
  docs/getting_help.rst
Labels: documentation, ICCS

#481 Wrap the ncOpen calls to append the file name to the exception message.
  core/src/ParaGridIO.cpp
  core/src/StructureFactory.cpp
  core/test/ParaGrid_test.cpp
Labels: enhancement, ICCS

#486 Coordinates for the 'simple rectangular' test
  core/src/CommandLineParser.cpp
  run/config_simple_example.cfg
  run/make_init.py
Labels: bug, ICCS

#484 add support for virtual environments to CMake
  .github/workflows/clang-compile-tests.yml
  CMakeLists.txt
  core/src/modules/CMakeLists.txt
  physics/src/modules/CMakeLists.txt
  physics/test/CMakeLists.txt
  run/CMakeLists.txt
Labels: bug, enhancement
