Repository nextsimhub/nextsimdg, pull requests merged in 2024-11, with the labels that each got.

#728 Prepare for setting XIOS up via nextSIM-DG
  core/src/ModelArray.cpp
  core/src/Xios.cpp
  core/src/include/ModelArray.hpp
  core/test/XiosGrid_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
  core/test/xios_test_input.cdl
Labels: ICCS

#729 Fixes for XIOS install and Docker build
  .github/workflows/docker.yml
  Dockerfiles/install-xios.sh
  docs/installation.rst
Labels: bug, ICCS

#738 Handle XIOS contexts
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosReadWrite_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#743 Initialise Shared::DAMAGE in PrognosticData::update
  core/src/PrognosticData.cpp
  physics/src/modules/DamageHealingModule/ConstantHealing.cpp
  physics/src/modules/DamageHealingModule/include/NoHealing.hpp
  physics/src/modules/include/IDamageHealing.hpp
  physics/test/DamageHealing_test.cpp
  physics/test/IceGrowth_test.cpp
Labels: bug

#745 Fix Mac CI
  .github/workflows/test_suite.yml
Labels: bug, ICCS, testing
