Repository nextsimhub/nextsimdg, pull requests merged in 2024-12, with the labels that each got.

#737 Abort git commit if pre-commit applies formatting
  .pre-commit
Labels: enhancement

#749 Fix up the Model class help.
  core/src/Model.cpp
Labels: documentation, ICCS

#750 Allow timestep to be set when XIOS handler is created
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosReadWrite_test.cpp
Labels: enhancement

#760 Workflow handling
  .github/workflows/linting.yml
  .github/workflows/test_suite.yml
Labels: enhancement, ICCS, testing
