Repository nextsimhub/nextsimdg, pull requests merged in 2024-10, with the labels that each got.

#685 Issue 614 ParaGridIO
  core/src/ParaGridIO.cpp
  core/src/include/ParaGridIO.hpp
Labels: bug, enhancement

#655 Get the ice-ocean stress into the ModelArrayRef system
  core/src/include/ModelComponent.hpp
  core/src/include/gridNames.hpp
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/include/IDynamics.hpp
  core/src/modules/include/ProtectedArrayNames.ipp
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
  dynamics/test/AdvectionPeriodicBC_test.cpp
  dynamics/test/Advection_test.cpp
Labels: enhancement

#662 Issue538 seasurfaceheight
  core/src/include/ModelComponent.hpp
  core/src/include/gridNames.hpp
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/include/IDynamics.hpp
  core/src/modules/include/ProtectedArrayNames.ipp
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/ParametricMap.cpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/DynamicsParameters.hpp
  dynamics/src/include/ParametricMap.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
  physics/src/modules/OceanBoundaryModule/BenchmarkOcean.cpp
  physics/src/modules/OceanBoundaryModule/ConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/ConstantOceanBoundary.cpp
  physics/src/modules/OceanBoundaryModule/FluxConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/TOPAZOcean.cpp
  physics/src/modules/OceanBoundaryModule/UniformOcean.cpp
  physics/src/modules/include/IOceanBoundary.hpp
  physics/test/TOPAZOcn_test.cpp
  physics/test/topaz_test_data.py
  run/era5_topaz4_maker.py
Labels: enhancement

#712 Zero out the high DG components when setting forcing data.
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/DynamicsKernel.hpp
Labels: bug, ICCS

#682 Improve execution speed of BBM stress update
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/ParametricMap.cpp
  dynamics/src/cgParametricMomentum.cpp
  dynamics/src/include/BBM.hpp
  dynamics/src/include/BBMStressUpdateStep.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/MEVPStressUpdateStep.hpp
  dynamics/src/include/ParametricMap.hpp
  dynamics/src/include/cgParametricMomentum.hpp
  dynamics/src/include/mevp.hpp
Labels: enhancement

#718 Fix a bug in BBM by adding a +1 to Pmax
  dynamics/src/include/BBMStressUpdateStep.hpp
Labels: bug

#715 No sea surface height
  core/src/ParaGridIO.cpp
  core/src/include/gridNames.hpp
  physics/src/modules/OceanBoundaryModule/TOPAZOcean.cpp
Labels: bug

#721 Hotfix for issue #720
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: bug
