Repository nextsimhub/nextsimdg, pull requests merged in 2024-02, with the labels that each got.

#487 Rename bare class name to include MEVP
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  core/src/modules/DynamicsModule/module.cfg
  dynamics/src/MEVPDynamicsKernel.cpp
  dynamics/src/include/MEVPDynamicsKernel.hpp
  run/config_dynamics_benchmark.cfg
Labels: enhancement, ICCS

#494 Add spack support
  docs/installation.rst
  spack.yaml
Labels: documentation, enhancement, ICCS

#489 Add Dockerfiles and document usage
  Dockerfiles/Dockerfile_Ubuntu
  Dockerfiles/Dockerfile_Ubuntu_MPI
  docs/installation.rst
Labels: documentation, enhancement, ICCS

#493 Documentation for running with MPI
  docs/getting_started.rst
  run/partition.cdl
  run/partition_metadata_2.cdl
Labels: documentation, ICCS

#498 Melt/issue378 dynamicsswitcher2
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/MEVPDynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: ICCS
