Repository nextsimhub/nextsimdg, pull requests merged in 2024-06, with the labels that each got.

#564 Hotfix for issue where initial files using the missing_value attribute don't work
  run/make_init_base.py
Labels: bug

#555 Wrap XIOS API calls part 1: getters
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosInit_test.cpp
  core/test/iodef.xml
Labels: enhancement, ICCS

#559 Wrap XIOS API calls part 2: setters
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosInit_test.cpp
  core/test/iodef.xml
Labels: enhancement, ICCS

#574 Remove calendar info from XIOS test XML file
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosInit_test.cpp
  core/test/iodef.xml
Labels: enhancement, ICCS

#576 Use `size_t` for sizes in XIOS interface
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/XiosInit_test.cpp
Labels: enhancement, ICCS

#584 Use neXtSIM-DG date/duration formats in `Xios`
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosInit_test.cpp
Labels: enhancement, ICCS

#585 Use `const` qualifiers in XIOS interface
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/XiosInit_test.cpp
Labels: enhancement, ICCS

#588 Split up XIOS tests per concept
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/CMakeLists.txt
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosInit_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#591 Eliminate Module warnings from tests.
  physics/test/ERA5Atm_test.cpp
  physics/test/IceGrowth_test.cpp
Labels: bug, ICCS
