Repository nextsimhub/nextsimdg, pull requests merged in 2024-08, with the labels that each got.

#630 Drop XIOS `isDefined*` and `areDefined*` methods
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/XiosAxis_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
Labels: ICCS

#632 Wrap XIOS frequency splitting and fix timestep bug
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosWrite_test.cpp
Labels: bug, enhancement, ICCS

#637 XIOS duration handling
  core/src/Time.cpp
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/Time_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosWrite_test.cpp
Labels: bug, enhancement, ICCS

#560 Add MPI support to ParaGrid
  .github/workflows/clang-compile-tests.yml
  core/src/ModelArray.cpp
  core/src/ParaGridIO.cpp
  core/src/ParallelNetcdfFile.cpp
  core/src/discontinuousgalerkin/ModelArrayDetails.cpp
  core/src/finitevolume/ModelArrayDetails.cpp
  core/src/include/ModelArray.hpp
  core/src/include/ParaGridIO.hpp
  core/src/include/ParallelNetcdfFile.hpp
  core/src/modules/StructureModule/include/ParametricGrid.hpp
  core/test/CMakeLists.txt
  core/test/ConfigOutput_test.cpp
  core/test/ParaGrid_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
  core/test/old_names.py
  core/test/partition_metadata_2.cdl
  core/test/testmodelarraydetails/ModelArrayDetails.cpp
  dynamics/test/CMakeLists.txt
  physics/test/CMakeLists.txt
  physics/test/ERA5Atm_test.cpp
  physics/test/TOPAZOcn_test.cpp
  run/make_init_para24x30.py
Labels: ICCS

#635 XIOS: use Domain for xy-plane and Axis for z
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#639 Use `REQUIRE_THROWS` in XIOS tests
  core/src/Xios.cpp
  core/src/include/xios_c_interface.hpp
  core/test/XiosAxis_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
Labels: bug, enhancement, ICCS

#652 Use updated `domain_decomp` naming scheme
  .github/workflows/clang-compile-tests.yml
  core/src/ModelMetadata.cpp
  core/test/partition_metadata_2.cdl
  core/test/partition_metadata_3.cdl
  run/partition.cdl
  run/partition_metadata_2.cdl
Labels: enhancement, ICCS

#653 Issue648 cmake refactor
  CMakeLists.txt
  core/CMakeLists.txt
  core/src/CMakeLists.txt
  core/src/modules/CMakeLists.txt
  core/test/CMakeLists.txt
  dynamics/CMakeLists.txt
  dynamics/src/CMakeLists.txt
  dynamics/test/CMakeLists.txt
  physics/CMakeLists.txt
  physics/src/CMakeLists.txt
  physics/src/modules/CMakeLists.txt
  physics/test/CMakeLists.txt
  run/CMakeLists.txt
Labels: enhancement

#642 Use doctest in advection test cases
  dynamics/test/AdvectionPeriodicBC_test.cpp
  dynamics/test/Advection_test.cpp
Labels: enhancement, ICCS

#647 Set up periodic Docker build
  .github/workflows/clang_format.yml
  .github/workflows/docker.yml
  .github/workflows/test_suite.yml
  Dockerfiles/Dockerfile.devenv
  Dockerfiles/spack.yaml
  spack.yaml
Labels: ICCS, testing

#644 Make the advected field type array non-const
  dynamics/src/include/DynamicsKernel.hpp
Labels: bug, ICCS

#661 Add explicit specialization of the base class to module.cpp
  scripts/module_builder.py
Labels: bug

#660 Add pre-commit for automatically updating date stamps
  .pre-commit
  README.md
Labels: enhancement
