Repository nextsimhub/nextsimdg, pull requests merged in 2024-07, with the labels that each got.

#598 Fixes to a few BBM issues
  core/src/PrognosticData.cpp
  core/src/include/ModelComponent.hpp
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/include/ProtectedArrayNames.ipp
  core/src/modules/include/SharedArrayNames.ipp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  run/make_init_base.py
  run/make_init_benchmark.py
  run/make_init_column.py
Labels: bug

#596 Use `Nextsim` namespace for XIOS tests
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#600 Default the initial 'lastOutputTime' to the model start time.
  core/src/DevStep.cpp
  core/src/modules/DiagnosticOutputModule/ConfigOutput.cpp
  core/src/modules/DiagnosticOutputModule/include/ConfigOutput.hpp
  core/src/modules/include/IDiagnosticOutput.hpp
Labels: bug, ICCS

#615 New ``model.missing_value``
  core/src/MissingData.cpp
Labels: enhancement

#556 Reinstantiate Dynamic Tests and add to CI
  .github/workflows/clang-compile-tests.yml
  dynamics/CMakeLists.txt
  dynamics/src/Interpolations.cpp
  dynamics/src/include/dgLimit.hpp
  dynamics/test/AdvectionPeriodicBC_test.cpp
  dynamics/test/Advection_test.cpp
  dynamics/test/CMakeLists.txt
  dynamics/test/FakeSmeshData.cpp
  dynamics/test/ParametricMesh_test.cpp
  dynamics/test/README.md
Labels: enhancement, ICCS, testing

#607 Healing module
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  physics/src/IceGrowth.cpp
  physics/src/include/IceGrowth.hpp
  physics/src/modules/DamageHealingModule/ConstantHealing.cpp
  physics/src/modules/DamageHealingModule/include/ConstantHealing.hpp
  physics/src/modules/DamageHealingModule/include/NoHealing.hpp
  physics/src/modules/DamageHealingModule/module.cfg
  physics/src/modules/include/IDamageHealing.hpp
  physics/src/modules/include/ILateralIceSpread.hpp
  physics/test/CMakeLists.txt
  physics/test/DamageHealing_test.cpp
  run/make_init_benchmark.py
Labels: enhancement

#617 Format dynamics code
  .github/workflows/clang-compile-tests.yml
  dynamics/CMakeLists.txt
  dynamics/src/DGTransport.cpp
  dynamics/src/DummyDynamicsKernel.cpp
  dynamics/src/DynamicsKernel.cpp
  dynamics/src/Interpolations.cpp
  dynamics/src/ParametricMap.cpp
  dynamics/src/ParametricMesh.cpp
  dynamics/src/ParametricTools.cpp
  dynamics/src/cgParametricMomentum.cpp
  dynamics/src/include/BBM.hpp
  dynamics/src/include/BBMDynamicsKernel.hpp
  dynamics/src/include/BBMStressUpdateStep.hpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/CGModelArray.hpp
  dynamics/src/include/CheckPoints.hpp
  dynamics/src/include/DGModelArray.hpp
  dynamics/src/include/DGTransport.hpp
  dynamics/src/include/DummyDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
  dynamics/src/include/IDynamicsUpdate.hpp
  dynamics/src/include/Interpolations.hpp
  dynamics/src/include/MEB.hpp
  dynamics/src/include/MEBParameters.hpp
  dynamics/src/include/MEVPDynamicsKernel.hpp
  dynamics/src/include/MEVPStressUpdateStep.hpp
  dynamics/src/include/NextsimDynamics.hpp
  dynamics/src/include/ParametricMap.hpp
  dynamics/src/include/ParametricMesh.hpp
  dynamics/src/include/ParametricTools.hpp
  dynamics/src/include/StressUpdateStep.hpp
  dynamics/src/include/Tools.hpp
  dynamics/src/include/VectorManipulations.hpp
  dynamics/src/include/cgParametricMomentum.hpp
  dynamics/src/include/cgVector.hpp
  dynamics/src/include/codeGenerationCGToDG.hpp
  dynamics/src/include/codeGenerationCGinGauss.hpp
  dynamics/src/include/codeGenerationDGinGauss.hpp
  dynamics/src/include/dgLimit.hpp
  dynamics/src/include/dgVector.hpp
  dynamics/src/include/dgVisu.hpp
  dynamics/src/include/mevp.hpp
  dynamics/src/include/stopwatch.hpp
  dynamics/test/25km_NH.smesh
  dynamics/test/AdvectionPeriodicBC_test.cpp
  dynamics/test/Advection_test.cpp
  dynamics/test/CGModelArray_test.cpp
  dynamics/test/CMakeLists.txt
  dynamics/test/DGModelArray_test.cpp
  dynamics/test/FakeSmeshData.cpp
  dynamics/test/FakeSmeshData.hpp
  dynamics/test/ParametricMesh_test.cpp
  dynamics/test/README.md
  dynamics/tests/CMakeLists.txt
Labels: ICCS

#606 Add DG components to the restart files
  CMakeLists.txt
  core/src/DevStep.cpp
  core/src/Model.cpp
  core/src/PDWriter.cpp
  core/src/PrognosticData.cpp
  core/src/discontinuousgalerkin/ModelArrayDetails.cpp
  core/src/include/OutputSpec.hpp
  core/src/include/PrognosticData.hpp
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/DynamicsModule/include/BBMDynamics.hpp
  core/src/modules/DynamicsModule/include/FreeDriftDynamics.hpp
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  core/src/modules/include/IDynamics.hpp
  core/test/CMakeLists.txt
  core/test/PrognosticDataIO_test.cpp
  core/test/PrognosticData_test.cpp
  docs/installation.rst
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/BBMDynamicsKernel.hpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
  dynamics/src/include/MEVPDynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: enhancement, ICCS

#575 Pass `ModelArray` to `Xios.write`, rather than array of `double`s
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/CMakeLists.txt
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#624 Issue622 netcdfheaders
  core/src/ModelMetadata.cpp
  core/src/RectGridIO.cpp
  core/src/include/ModelMetadata.hpp
Labels: enhancement, ICCS

#631 Ignore empty modules
  core/src/modules/CMakeLists.txt
  physics/src/modules/CMakeLists.txt
Labels: bug, ICCS
