Repository nextsimhub/nextsimdg, pull requests merged in 2024-09, with the labels that each got.

#673 Remove timer classes.
  core/src/CMakeLists.txt
  core/src/ScopedTimer.cpp
  core/src/Timer.cpp
  core/src/include/ScopedTimer.hpp
  core/src/include/Timer.hpp
  core/test/CMakeLists.txt
  core/test/ScopedTimer_test.cpp
  core/test/Timer_test.cpp
Labels: enhancement

#675 Remove the static implementaion of NullIterator.
  core/src/Iterator.cpp
  core/src/include/Iterator.hpp
Labels: enhancement

#686 Change ConfigMap static constants to an enum.
  core/src/CommonRestartMetadata.cpp
  core/src/include/ConfigMap.hpp
Labels: enhancement

#687 Remove the FileCallbackCloser static list.
  core/src/FileCallbackCloser.cpp
  core/src/include/FileCallbackCloser.hpp
Labels: enhancement

#691 Localize Configured keyMaps
  core/src/Model.cpp
  core/src/ModelConfig.cpp
  core/src/include/Configured.hpp
  core/src/include/ModelConfigMapElements.ipp
  core/src/modules/DiagnosticOutputModule/ConfigOutput.cpp
  core/test/Configurator_test.cpp
  physics/src/IceGrowth.cpp
  physics/src/SlabOcean.cpp
  physics/src/modules/AtmosphereBoundaryModule/ConfiguredAtmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/ERA5Atmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/FluxConfiguredAtmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/MU71Atmosphere.cpp
  physics/src/modules/DamageHealingModule/ConstantHealing.cpp
  physics/src/modules/FluxCalculationModule/FiniteElementFluxes.cpp
  physics/src/modules/IceThermodynamicsModule/ThermoIce0.cpp
  physics/src/modules/IceThermodynamicsModule/ThermoWinton.cpp
  physics/src/modules/LateralIceSpreadModule/HiblerSpread.cpp
  physics/src/modules/OceanBoundaryModule/ConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/FluxConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/TOPAZOcean.cpp
Labels: bug

#677 Issue614 missing data
  core/src/CMakeLists.txt
  core/src/MissingData.cpp
  core/src/Model.cpp
  core/src/ModelComponent.cpp
  core/src/ModelConfig.cpp
  core/src/ParaGridIO.cpp
  core/src/RectGridIO.cpp
  core/src/include/MissingData.hpp
Labels: enhancement

#696 Remove static data from Configurator.
  core/src/Configurator.cpp
  core/src/include/Configurator.hpp
Labels: enhancement

#704 Issue 614 Module & ConfiguredModule
  core/src/ConfiguredModule.cpp
  core/src/DevStep.cpp
  core/src/Model.cpp
  core/src/ModelMetadata.cpp
  core/src/PrognosticData.cpp
  core/src/StructureFactory.cpp
  core/src/include/ConfiguredModule.hpp
  core/src/include/Module.hpp
  core/src/include/NextsimModule.hpp
  core/src/main.cpp
  core/src/modules/CMakeLists.txt
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  core/test/ConfigOutput_test.cpp
  core/test/ConfiguredModule_test.cpp
  core/test/DynamicsModuleForPDtest.cpp
  core/test/ModuleLoaderTestModules/moduleLoaderAssignments.ipp
  core/test/ModuleLoaderTestModules/moduleLoaderFunctions.ipp
  core/test/ModuleLoaderTestModules/moduleLoaderHeaders.ipp
  core/test/ModuleLoaderTestModules/moduleLoaderNames.ipp
  core/test/ModuleLoaderTestModules/modules.json
  core/test/ParaGrid_test.cpp
  core/test/PrognosticDataIO_test.cpp
  core/test/PrognosticData_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
  core/test/moduleTestClasses.hpp
  physics/src/IceGrowth.cpp
  physics/src/modules/AtmosphereBoundaryModule/ConfiguredAtmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/ERA5Atmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/MU71Atmosphere.cpp
  physics/src/modules/CMakeLists.txt
  physics/src/modules/FluxCalculationModule/FiniteElementFluxes.cpp
  physics/src/modules/IceThermodynamicsModule/ThermoIce0.cpp
  physics/src/modules/OceanBoundaryModule/ConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/ConstantOceanBoundary.cpp
  physics/src/modules/OceanBoundaryModule/FluxConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/TOPAZOcean.cpp
  physics/src/modules/OceanBoundaryModule/UniformOcean.cpp
  physics/test/BasicIceOceanFlux_test.cpp
  physics/test/ConfiguredAtmosphere_test.cpp
  physics/test/DamageHealing_test.cpp
  physics/test/ERA5Atm_test.cpp
  physics/test/FiniteElementFluxes_test.cpp
  physics/test/IceGrowth_test.cpp
  physics/test/ThermoIce0Temperature_test.cpp
  physics/test/ThermoIce0_test.cpp
  physics/test/ThermoWintonTemperature_test.cpp
  physics/test/UniformOcean_test.cpp
  scripts/module_builder.py
  scripts/module_header.py
Labels: bug, enhancement

#707 bugfix: relax cmake version to remove deprecated version
  Dockerfiles/spack.yaml
  spack.yaml
Labels: ICCS
