Repository nextsimhub/nextsimdg, pull requests merged in 2024-05, with the labels that each got.

#496 Xios interface with tests
  .github/workflows/clang-compile-tests.yml
  .github/xios_arch/ubuntu.arch
  .github/xios_arch/ubuntu.env
  .github/xios_arch/ubuntu.fcm
  .gitignore
  CMakeLists.txt
  Dockerfiles/Dockerfile.devenv
  Dockerfiles/Dockerfile.production
  Dockerfiles/Dockerfile_Ubuntu
  Dockerfiles/Dockerfile_Ubuntu_MPI
  Dockerfiles/install-xios.sh
  Dockerfiles/spack.yaml
  cmake/Findxios.cmake
  core/src/CMakeLists.txt
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/src/include/xios_c_interface.hpp
  core/test/CMakeLists.txt
  core/test/XiosInit_test.cpp
  core/test/iodef.xml
  docs/installation.rst
  spack.yaml
Labels: ICCS

#540 Improve clang format
  .github/workflows/clang-compile-tests.yml
Labels: ICCS

#542 Issue533 init maker
  physics/src/BenchmarkCoordinates.cpp
  physics/src/modules/AtmosphereBoundaryModule/BenchmarkAtmosphere.cpp
  physics/test/BenchmarkBoundaries_test.cpp
  run/config_benchmark.cfg
  run/make_init_base.py
  run/make_init_benchmark.py
  run/make_init_column.py
Labels: enhancement

#525 Issue512 benchmark2
  run/CMakeLists.txt
Labels: enhancement

#548 Dynamics with spherical coordinates
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: bug, ICCS

#551 Dimension names
  core/src/ParaGridIO.cpp
  core/src/RectGridIO.cpp
  core/src/discontinuousgalerkin/ModelArrayDetails.cpp
  core/src/finitevolume/ModelArrayDetails.cpp
  run/make_init.py
  run/make_init25kmNH.py
  run/make_init25kmNH_test.py
  run/make_init_base.py
  run/make_init_para24x30.py
  run/make_init_rect20x30.py
  test/ThermoIntegration_test.py
Labels: bug, enhancement, ICCS

#528 Dynamics references
  dynamics/src/include/BBMStressUpdateStep.hpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/MEVPStressUpdateStep.hpp
  dynamics/src/include/StressUpdateStep.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: enhancement, ICCS

#557 Dimension names redux
  core/src/ParaGridIO.cpp
  core/src/RectGridIO.cpp
  core/src/discontinuousgalerkin/ModelArrayDetails.cpp
  core/src/finitevolume/ModelArrayDetails.cpp
  core/src/include/ModelArray.hpp
  core/test/CMakeLists.txt
  core/test/ParaGrid_test.cpp
  core/test/old_names.py
  core/test/testmodelarraydetails/ModelArrayDetails.cpp
  run/era5_topaz4_maker.py
Labels: enhancement, ICCS

#522 Free drift dynamics: now with dynamics switcher!
  core/src/modules/DynamicsModule/include/FreeDriftDynamics.hpp
  core/src/modules/DynamicsModule/module.cfg
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
Labels: enhancement
