Repository nextsimhub/nextsimdg, pull requests merged in 2024-03, with the labels that each got.

#506 Simple 2D ParametricGrid restart file
  physics/src/modules/AtmosphereBoundaryModule/FluxConfiguredAtmosphere.cpp
  run/CMakeLists.txt
  run/config_para24x30.cfg
  run/make_init_para24x30.py
Labels: enhancement, ICCS

#511 Add the evap key.
  physics/src/modules/AtmosphereBoundaryModule/FluxConfiguredAtmosphere.cpp
Labels: bug, documentation, ICCS

#509 Require only Python interpreter
  CMakeLists.txt
Labels: ICCS

#518 Install numpy from pip3.
  .github/workflows/clang-compile-tests.yml
Labels: bug, ICCS

#514 Issue513 rect grid test improvements
  core/src/RectGridIO.cpp
  core/test/CMakeLists.txt
  core/test/RectGrid_test.cpp
  core/test/partition_metadata_3.nc.dump
Labels: ICCS

#516 Issue515 domain decompose refactor
  core/src/Model.cpp
  core/src/ModelMetadata.cpp
  core/src/RectGridIO.cpp
  core/src/StructureFactory.cpp
  core/src/include/ModelMetadata.hpp
  core/src/include/RectGridIO.hpp
  core/src/include/StructureFactory.hpp
  core/src/modules/StructureModule/include/ParametricGrid.hpp
  core/src/modules/StructureModule/include/RectangularGrid.hpp
  core/src/modules/include/IStructure.hpp
  core/test/RectGrid_test.cpp
Labels: ICCS
