Repository nextsimhub/nextsimdg, pull requests merged in 2025-05, with the labels that each got.

#811 Update GH workflows
  .github/workflows/docker.yml
  .github/workflows/doxygen.yml
  .github/workflows/linting.yml
  .github/workflows/test_suite.yml
  Dockerfiles/Dockerfile.devenv
Labels: ICCS

#757 Align update of nextSIM-DG and XIOS calendars
  .github/workflows/test_suite.yml
  Dockerfiles/install-xios.sh
  core/src/CMakeLists.txt
  core/src/ModelMetadata.cpp
  core/src/ParaGridIO.cpp
  core/src/Xios.cpp
  core/src/include/ModelMetadata.hpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/ConfigOutput_test.cpp
  core/test/ParaGrid_test.cpp
  core/test/RectGrid_test.cpp
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosReadWrite_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#758 Set up `ParaGridIO_Xios` as a copy of `ParaGridIO` for now
  core/src/CMakeLists.txt
  core/src/ParaGridIO_Xios.cpp
Labels: enhancement, ICCS

#824 Configure XIOS from `.cfg` file
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/XiosCalendar_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#832 Xios config output fix
  .github/workflows/test_suite.yml
  core/test/ConfigOutput_test.cpp
  core/test/XiosRead_test.cpp
Labels: bug, ICCS

#820 Use overElements in IOceanBoundary and derived classes
  physics/src/SlabOcean.cpp
  physics/src/include/SlabOcean.hpp
  physics/src/modules/include/IOceanBoundary.hpp
Labels: enhancement

#813 Enable more numbers of MPI ranks in XIOS tests
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
Labels: ICCS, testing

#834 XIOS: Determine read/write access of fields from config
  core/src/ParaGridIO_Xios.cpp
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/CMakeLists.txt
  core/test/ParaGrid_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#836 XIOS: Create files from config upon initialisation
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/XiosFile_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: enhancement, ICCS

#838 Add getConfiguration(), rework getState*().
  core/src/DevStep.cpp
  core/src/PDWriter.cpp
  core/src/PrognosticData.cpp
  core/src/include/ModelComponent.hpp
  core/src/include/PrognosticData.hpp
  core/src/modules/DiagnosticOutputModule/ConfigOutput.cpp
  core/src/modules/DiagnosticOutputModule/include/ConfigOutput.hpp
  core/src/modules/DiagnosticOutputModule/include/NoOutput.hpp
  core/src/modules/DiagnosticOutputModule/include/SimpleOutput.hpp
  core/src/modules/DynamicsModule/BBMDynamics.cpp
  core/src/modules/DynamicsModule/MEVPDynamics.cpp
  core/src/modules/DynamicsModule/include/BBMDynamics.hpp
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  core/src/modules/include/IDynamics.hpp
  core/test/ModelComponent_test.cpp
  core/test/PDTestDynamics.hpp
  physics/src/IceGrowth.cpp
  physics/src/SlabOcean.cpp
  physics/src/include/IceGrowth.hpp
  physics/src/include/SlabOcean.hpp
  physics/src/modules/AtmosphereBoundaryModule/ConfiguredAtmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/ERA5Atmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/FluxConfiguredAtmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/MU71Atmosphere.cpp
  physics/src/modules/AtmosphereBoundaryModule/include/ConfiguredAtmosphere.hpp
  physics/src/modules/AtmosphereBoundaryModule/include/ERA5Atmosphere.hpp
  physics/src/modules/AtmosphereBoundaryModule/include/FluxConfiguredAtmosphere.hpp
  physics/src/modules/AtmosphereBoundaryModule/include/MU71Atmosphere.hpp
  physics/src/modules/DamageHealingModule/ConstantHealing.cpp
  physics/src/modules/DamageHealingModule/include/ConstantHealing.hpp
  physics/src/modules/DamageHealingModule/include/NoHealing.hpp
  physics/src/modules/FluxCalculationModule/FiniteElementFluxes.cpp
  physics/src/modules/FluxCalculationModule/include/FiniteElementFluxes.hpp
  physics/src/modules/IceThermodynamicsModule/ThermoIce0.cpp
  physics/src/modules/IceThermodynamicsModule/ThermoWinton.cpp
  physics/src/modules/IceThermodynamicsModule/include/DummyIceThermodynamics.hpp
  physics/src/modules/IceThermodynamicsModule/include/ThermoIce0.hpp
  physics/src/modules/IceThermodynamicsModule/include/ThermoWinton.hpp
  physics/src/modules/LateralIceSpreadModule/HiblerSpread.cpp
  physics/src/modules/LateralIceSpreadModule/include/DummyIceSpread.hpp
  physics/src/modules/LateralIceSpreadModule/include/HiblerSpread.hpp
  physics/src/modules/OceanBoundaryModule/ConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/FluxConfiguredOcean.cpp
  physics/src/modules/OceanBoundaryModule/TOPAZOcean.cpp
  physics/src/modules/OceanBoundaryModule/include/ConfiguredOcean.hpp
  physics/src/modules/OceanBoundaryModule/include/FluxConfiguredOcean.hpp
  physics/src/modules/OceanBoundaryModule/include/TOPAZOcean.hpp
  physics/src/modules/include/IAtmosphereBoundary.hpp
  physics/src/modules/include/IDamageHealing.hpp
  physics/src/modules/include/IFluxCalculation.hpp
  physics/src/modules/include/IIceOceanHeatFlux.hpp
  physics/src/modules/include/IIceThermodynamics.hpp
  physics/src/modules/include/ILateralIceSpread.hpp
  physics/src/modules/include/IOceanBoundary.hpp
  physics/test/BasicIceOceanFlux_test.cpp
  physics/test/DamageHealing_test.cpp
  physics/test/FiniteElementFluxes_test.cpp
  physics/test/IceGrowth_test.cpp
  physics/test/ThermoIce0_test.cpp
  physics/test/ThermoWintonTemperature_test.cpp
Labels: enhancement, ICCS

#841 Issue840 Fixing `ConfigOutput_test` to be deterministic
  core/src/include/ModelMetadata.hpp
  core/test/ConfigOutput_test.cpp
Labels: bug

#845 Issue734 add ctest functionality
  .github/workflows/test_suite.yml
  CMakeLists.txt
  core/CMakeLists.txt
  core/test/CMakeLists.txt
  docs/installation.rst
  dynamics/CMakeLists.txt
  dynamics/test/CMakeLists.txt
  physics/CMakeLists.txt
  physics/test/CMakeLists.txt
Labels: ICCS
