Repository nextsimhub/nextsimdg, pull requests merged in 2025-04, with the labels that each got.

#807 bugfix: add cmake support for netcdf-cxx
  CMakeLists.txt
  cmake/FindNetCDF.cmake
Labels: bug, ICCS

#805 Ice ocean stress computation
  core/src/modules/DynamicsModule/include/BBMDynamics.hpp
  core/src/modules/DynamicsModule/include/MEVPDynamics.hpp
  dynamics/src/CGDynamicsKernel.cpp
  dynamics/src/include/BBMDynamicsKernel.hpp
  dynamics/src/include/BrittleCGDynamicsKernel.hpp
  dynamics/src/include/CGDynamicsKernel.hpp
  dynamics/src/include/DynamicsKernel.hpp
  dynamics/src/include/FreeDriftDynamicsKernel.hpp
  dynamics/src/include/MEVPDynamicsKernel.hpp
  dynamics/src/include/VPCGDynamicsKernel.hpp
Labels: enhancement

#816 ci: install pip manually and use venv for nextsim
  .github/workflows/test_suite.yml
Labels: bug, ICCS

#822 Set up `Finalizer` for XIOS
  core/src/Xios.cpp
  core/src/include/Xios.hpp
  core/test/ConfigOutput_test.cpp
  core/test/ParaGrid_test.cpp
  core/test/XiosAxis_test.cpp
  core/test/XiosCalendar_test.cpp
  core/test/XiosDomain_test.cpp
  core/test/XiosField_test.cpp
  core/test/XiosFile_test.cpp
  core/test/XiosGrid_test.cpp
  core/test/XiosRead_test.cpp
  core/test/XiosWrite_test.cpp
Labels: bug
